name: Site Monitor
on:
  schedule:
    # - cron: '*/15 * * * *'  # Запуск каждые 15 минут
        # Запуск каждые 15 минут, но со смещением в 2 минуты
    - cron: '2,17,32,47 * * * *'  # :02, :17, :32, :47
  workflow_dispatch:  # Ручной запуск

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run monitoring script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor.py
